version: "3.9"
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONUNBUFFERED=1
      - WATCH_SOURCE="/app"
      - WATCH_USEPOLLING=true
    command: bash -c "watchmedo auto-restart --directory=/app --pattern=*.py -- uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
